// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0a
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from 
// c:\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1494

#ifndef MESSENGER_I_IHF9AB_H_
#define MESSENGER_I_IHF9AB_H_

#include "corba_file/MessengerS.h"
#include <QObject>

#include <iostream>

#include "ace/OS_NS_unistd.h"
#include "ace/OS_NS_sys_time.h"


#include "mainwindow.h"
#include "ui_mainwindow.h"

#include "myrunnablemessagelogicsentback.h"
//#include "myobjectmessagelogicbacksent.h"


#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


typedef ::LocalInterface::CompositeTypes::cmdUpdateParametersCompTypeNew  cmpNEW;
typedef ::LocalInterface::CompositeTypes::cmdUpdateParametersCompType  cmp;
typedef ::LocalInterface::CompositeTypes::cmdUpdateParametersCompTypeLogic  cmpLogic;
typedef ::CORBA::Long CORBALong;

class  Messenger_i
  : public QObject, public virtual POA_Messenger
{
    Q_OBJECT


signals:
  void MessSent(QString,QString,CORBALong, QString, QString);
  void cmdUpdateParametersNewSent(cmpNEW);
  void cmdUpdateParametersSent(cmp);
  void cmdUpdateParametersLogicSent(cmpLogic);


public:
  // Constructor 
  Messenger_i (CORBA::ORB_ptr orb,
               int instance);



  // Destructor 
  virtual ~Messenger_i (void);

  virtual
   ::CORBA::Boolean send_message (
     const char * Name,
     const char * LastName,
     ::CORBA::Long eta,
     const char * subject,
     const char * message);

  virtual
  void cmdUpdateParameters (
    const ::LocalInterface::CompositeTypes::cmdUpdateParametersCompType & cmdUpdateParametersParam);

  virtual
  void cmdUpdateParametersNew (
    const ::LocalInterface::CompositeTypes::cmdUpdateParametersCompTypeNew & cmdUpdateParametersParamNew);

  virtual
   void cmdUpdateParametersLogic (
     const ::LocalInterface::CompositeTypes::cmdUpdateParametersCompTypeLogic & cmdUpdateParametersParamLogic);

private:

  QObject *parentLocal;


  int instance_;

  CORBA::Boolean small_request_status_;

  CORBA::Boolean large_request_status_;




};


#endif /* MESSENGER_I_H_  */
