// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0a
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1494

#ifndef MESSENGER2_I_IHF9AB_H_
#define MESSENGER2_I_IHF9AB_H_

#include <iostream>

#include "corba_file/Messenger2S.h"
#include "ace/OS_NS_unistd.h"
#include "ace/OS_NS_sys_time.h"

#include "mainwindow.h"
#include "ui_mainwindow.h"

#include <QThreadPool>
#include <QObject>

#include "myrunnablemessagelogicsent.h"
//#include "myobjectmessagelogicsent.h"



#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */



typedef ::CORBA::Long CORBALong;
typedef ::LocalInterface::CompositeTypes::cmdUpdateParametersCompTypeLogic  cmpLogic;

class  Messenger2_i
  : public QObject, public virtual POA_Messenger2
{
    Q_OBJECT


signals:
  void MessSent(QString,QString,CORBALong, QString, QString);
  void cmdUpdateParametersLogicBackSent(cmpLogic);



public:
  // Constructor
  Messenger2_i (void);



  // Destructor
  virtual ~Messenger2_i (void);


  virtual
  ::CORBA::Boolean send_message2 (
    const char * Name,
    const char * LastName,
    ::CORBA::Long eta,
    const char * subject,
    const char * message);

  virtual
  void cmdUpdateParametersLogicBack (
    const ::LocalInterface::CompositeTypes::cmdUpdateParametersCompTypeLogic & cmdUpdateParametersParamLogic);


private:

  QObject *parentLocal;


};


#endif /* MESSENGER2_I_H_  */
