module LocalInterface {
    
    module BaseTypes {
        
        
        typedef boolean tbBoolean;
        
        
        typedef short tnInt16;
        
        
        typedef long tnInt32;
        
        
        typedef string tnString;
        
        
        typedef unsigned short tnUInt16;
        
        
        typedef char tnUInt2;
        
        
        typedef unsigned long tnUInt32;
        
        
        typedef double trFloat64;
		
		
		enum SwitchNTP_ServerEnum {

            SwitchToPrimary,
            SwitchToSecondary,
            SwitchToInternal            
        };
		
		
		enum SourceDestinationEnum {

            MICS,
            Sensor,
            Launcher,
            Other            
        };
		
	};
	
	
	module CompositeTypes 
	{
        

		struct MessageHeaderStruct {
				LocalInterface::BaseTypes::SourceDestinationEnum Source;
				LocalInterface::BaseTypes::tnUInt32 ResponseID;
				LocalInterface::BaseTypes::tnUInt32 MessageLength;
				LocalInterface::BaseTypes::tnUInt32 MessageID;
				LocalInterface::BaseTypes::SourceDestinationEnum Destination;
				LocalInterface::BaseTypes::trFloat64 TimeStamp;
		};    
			
		struct cmdUpdateParametersCompType {
			LocalInterface::CompositeTypes::MessageHeaderStruct Header;
			LocalInterface::BaseTypes::tnUInt32 PrimaryNTP_ServIP_Addr;
			LocalInterface::BaseTypes::tnUInt32 SecondaryNTP_ServIP_Addr;
			LocalInterface::BaseTypes::tnInt16 TimeCorrection;
			LocalInterface::BaseTypes::tnUInt16 NTP_Threshold;
			LocalInterface::BaseTypes::tnUInt32 PrivateHostAddr;
			LocalInterface::BaseTypes::tnUInt32 PrivateHostMask;
			LocalInterface::BaseTypes::tnUInt16 PrivateHostPort;
			LocalInterface::BaseTypes::tnUInt32 PublicVoIP_Addr;
			LocalInterface::BaseTypes::tnUInt32 PublicVoIP_Mask;
			LocalInterface::BaseTypes::tnUInt16 PublicVoIP_Port;
			LocalInterface::BaseTypes::tnUInt32 PublicHostAddr;
			LocalInterface::BaseTypes::tnUInt32 PublicHostMask;
			LocalInterface::BaseTypes::tnUInt32 PrivateRR_EthernetAddr;
			LocalInterface::BaseTypes::tnUInt32 PrivateRR_Mask;
			LocalInterface::BaseTypes::tnUInt32 PublicRR_Addr;
			LocalInterface::BaseTypes::tnUInt32 PublicRR_Mask;
			LocalInterface::BaseTypes::tnUInt32 PrivateRP_Addr;
			LocalInterface::BaseTypes::tnUInt32 PrivateRP_Mask;
			LocalInterface::BaseTypes::tnUInt16 PrivateRP_Port;
			LocalInterface::BaseTypes::tnUInt32 PublicRP_Addr;
			LocalInterface::BaseTypes::tnUInt32 PublicRP_Mask;
			LocalInterface::BaseTypes::tnUInt32 MulticastGroupAddr;
			LocalInterface::BaseTypes::SwitchNTP_ServerEnum SwitchNTP_Server;
			LocalInterface::BaseTypes::tnUInt32 PrivateRR_FiberAddr;
		};
		
		
		struct cmdUpdateParametersCompTypeNew {
			LocalInterface::BaseTypes::tnUInt32 Val1;
			LocalInterface::BaseTypes::tnUInt32 Val2;
			LocalInterface::BaseTypes::tnInt16 Eta;
			LocalInterface::BaseTypes::tnUInt16 Figli;
			LocalInterface::BaseTypes::tnUInt32 Famigliari;
			LocalInterface::BaseTypes::tnUInt32 Tel1;
			LocalInterface::BaseTypes::tnUInt16 Tel2;
		};


		struct cmdUpdateParametersCompTypeLogic {
			LocalInterface::BaseTypes::tnInt16 Eta;
			LocalInterface::BaseTypes::tnUInt16 Figli;
			LocalInterface::BaseTypes::tnUInt32 Famigliari;
			LocalInterface::BaseTypes::tnUInt32 Tel;
		};
	};
};	

